### ISSUE TITLE
Meta endpoint will fail if a single node fails

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#17]
Reading from the meta endpoint will fail if a single node returns an error. This will result in a brittle endpoint on larger deployments. This resembles the pattern that Loggregator's TrafficController had for recent logs and container metrics.

**Comment by bradylove** [comment]
If any of the requests to remote nodes are sucessful we will return the partial meta data we were able to get. If all the requests fail we will return an error.
