### ISSUE TITLE
Change group API to better reflect it's nature

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#27]
The groups aggressively prune themselves and require a process to actively keep them up to date. Therefore the remove endpoint is not very useful.

Furthermore add seems misleading.

I propose that we remove the remove endpoint and replace the add with a "refresh" endpoint that receives an array of source IDs

**Comment by bradylove** [comment]
@apoydence "refresh" may be a bit confusing as well. To me if I see "refresh" there is some sort of initialization that should happen first. What about something more like `Set` and then the JSON request can be a `PUT` that has a JSON body with a slice of source ID's?

**Comment by poy** [comment]
@bradylove That makes sense to me. Does `Set` properly communicate that it must be invoked continuously? I feel that `Refresh` does have that implication.

**Comment by johannaratliff** [comment]
@apoydence either restore or recreate I feel would communicate that it needs to be called continuously but also actively re-makes the group. Options.

**Comment by poy** [comment]
@bradylove @JohannaSmith What about `SetEphemeral`? I think this indicates that there is not a preceding command and it spells out that the state will not be persisted.

**Comment by wfernandes** [comment]
I suggest `SetSource` along with documentation that indicates sources within the group will be expired after a default time period. The behavior that the group will automatically remove sources is the anomaly that needs to be documented. 
`SetEphemeral` may be confusing from the aspect of are the sources ephemeral or the group?

**Comment by poy** [comment]
@wfernandes I think it is worth mentioning that the entire group and its source IDs are ephemeral.

**Comment by poy** [comment]
Per a conversation with @wfernandes I think we should rename groups to `shard_groups` and add a concept within the `shard_group` called a `group`.

The `shard_group` is responsible for sharing data load across several `requester_id`s. The inner group is used ensure that a single requester can get metrics grouped together. 

For example:

If I need to calculate `(m1 + m2) / 100`, then I need to ensure that both `m1` and `m2` are egressed to the same requester. This would be the inner group. If this equation is one of many, where I would need to do calculations on `m1`, `m2` ... `m100`, then this is where a `shard_group` comes in handy. My many consuming instances would want to share the load of running the calculations.

**Comment by bradylove** [comment]
This was addressed in #34
