### ISSUE TITLE
Proposal: Metric Name filter

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#35]
The idea of filtering based on a name has been tossed around several times. If PromQL is considered, then it will be even more important. 

The name would have to come from multiple places based on the envelope type. However, I think this is a reasonable thing to do server side instead of client side.

**Comment by hev** [comment]
This is effectively accomplished by providing a log-query API that accepts promQL. Closing this issue in favor of a new story created to accomplish this.
