### ISSUE TITLE
Scheduler does not schedule immediately

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/log-cache#46]
When spinning up the scheduler I expected it to work immediately. Instead it took a minute for it to start working. 

Apparently, the ticker waits for an entire interval (defaults to one minute):

https://github.com/cloudfoundry/log-cache/blob/46a5495dd2f2271f81dc91b32c6ce27cbb17f435/scheduler.go#L185

Can the scheduler run once right when it comes up?

**Comment by toddboom** [comment]
Fixed with some lovely, idiomatic Go:
https://groups.google.com/forum/m/#!topic/golang-nuts/H_55uzPp98s

**Comment by toddboom** [comment]
This is fixed.
