### ISSUE TITLE
Bleeding secrets into logs

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/log-cache#50]
Looking at the `cf-auth-proxy` logs I noticed we were logging the UAA client secret as part of the envstruct report. I thought we just forgot to add `noreport` to the sturct tag but apparently it is a bug in `go-envstruct`.

https://github.com/cloudfoundry/go-envstruct/issues/7

Once that is fixed we should bump and ensure we do not log credentials.

**Comment by johannaratliff** [comment]
Using new go-envstruct has resolved this.
