### ISSUE TITLE
envelope_type filter for logcache /v1/read doesn't work

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/log-cache#53]
As can be seen below, in the output where the `envelope_type` was filtered to `counter|COUNTER` it included **gauge** values.
```
pivotal@crabapple loggregator-k8s-deployment $ curl -s "localhost:8081/v1/read/metron?envelope_type=counter" | jq .envelopes.batch[
5]
{
  "timestamp": "1525203780015364500",
  "source_id": "metron",
  "tags": {
    "loggregator": "v2",
    "metric_version": "2.0",
    "origin": "loggregator.metron"
  },
  "gauge": {
    "metrics": {
      "average_envelope": {
        "unit": "bytes/minute",
        "value": 276.59
      }
    }
  }
}
```

**Comment by bradylove** [comment]
@wfernandes `envelope_type` was changed to `envelope_types` which can accept multiple envelope types.

See https://github.com/cloudfoundry/log-cache/blob/master/api/v1/egress.proto#L27

It does seem that our documentation in the README is out of date though. We should fix that.

**Comment by thepeterstone** [comment]
@wfernandes Docs updated!
