### ISSUE TITLE
PromQL endpoint returns current epoch time for points instead of metric timestamp

### ISSUE THREAD

**Issue by iplay88keys** [cloudfoundry/log-cache#58]
When the PromQL endpoint is called with an instant query such as:

`query=CapacityRemainingMemory{source_id="rep"}`

we see the time constantly updating while the value stays the same until a new metric goes through the system.

Since these timestamps allow for both graphing and an understanding of when metrics were emitted, they should relate to the timestamp of the metric itself, not the time at which they were queried. Additionally, the resulting timestamps for each source are the same. If these were the metric timestamps, they would likely be different due to them coming from multiple sources with differing clocks.

**Reproduction Steps:**
1. Curl the PromQL endpoint with a query multiple times for a metric that is emitted infrequently `query=CapacityRemainingMemory{source_id="rep"}`
**Result**: See the timestamps on the points increase for each call
**Expected**: See the timestamps stay the same until a new metric is emitted

**Comment by iplay88keys** [comment]
@apoydence It looks like prometheus always returns the current timestamp for returned points.

**Comment by poy** [comment]
@iplay88keys The `time` value is a parameter that can be passed along with the `query` parameter. This is the value that you are seeing. This is also what Prometheus returns, so we believe it to be correct behavior.
