### ISSUE TITLE
PromQL endpoint returns only one point for metrics that should have multiple values over a range

### ISSUE THREAD

**Issue by iplay88keys** [cloudfoundry/log-cache#59]
When the PromQL endpoint is called with a range vector query such as:

`query=CapacityRemainingMemory{source_id="rep"}[10m]`

we see the number of points per sample is always one.

In order to take a rate, average over time, etc, we need multiple points to be returned (one for each metric emitted over that time period).

**Reproduction Steps:**
1. Curl the PromQL endpoint with a query for a metric that has been emitted multiple times in the time period `query=CapacityRemainingMemory{source_id="rep"}[10m]`
**Result**: See the number of points returned per sample stay at one.
**Expected**: See multiple points per sample.

**Comment by johannaratliff** [comment]
@iplay88keys Are you still experiencing this with latest log-cache? The story created for this issue didn't have a lot of resolution but it didn't seem like I was able to replicate.
