### ISSUE TITLE
PromQL emits unsorted data

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#62]
I would expect PromQL to return sorted data since log cache can sort data.

```
curl -s -G "http://log-cache.<system-domain>.com/v1/promql" --data-urlencode 'query=http{source_id="<sourceID>"}[2m]' -H"Authorization: $(cf oauth-token)" | jq . | grep time
            "time": "1525881083000000000",
            "time": "1525881084000000000",
            "time": "1525881084000000000",
            "time": "1525881085000000000",
            "time": "1525881085000000000",
            "time": "1525881067000000000",
            "time": "1525881082000000000",
            "time": "1525881083000000000",
```

/cc @johannasmith

**Comment by toddboom** [comment]
@apoydence I wasn't able to reproduce this. Could you post a full JSON response?

It seems like it might be possible that the grep is hiding underlying groupings that may have each been sorted correctly by time.

**Comment by poy** [comment]
@toddboom This looks like an old issue that has since been resolved. Closing.
