### ISSUE TITLE
Misleading configuration name

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#66]
https://github.com/cloudfoundry/log-cache/blob/fce9c70e29d2523edf11eb984d5683e853cb5a9b/cmd/group-reader/config.go#L26-L28

`MaxPerSource` implies that the max is per `SourceID` when in reality it is max per `RequesterID`. This means that for every requester to a group, it will have the set maximum.

**Comment by toddboom** [comment]
I think this feature has been deprecated and removed, so this is no longer actionable. Closing it out.
