### ISSUE TITLE
Log Cache does not have a metric for dropped envelopes

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#67]
It looks like Log Cache logs how many envelopes were dropped, however it does not have anything on its health endpoint. This is a vital metric.

https://github.com/cloudfoundry/log-cache/blob/81850b0272c9e59fc7396aeb93a30cb90555fc18/internal/routing/batched_ingress_client.go#L40

**Comment by johannaratliff** [comment]
Resolved. [Here](https://github.com/cloudfoundry/log-cache/blob/06968c0bc63f96498d511f1d65330c92b1660fce/internal/routing/batched_ingress_client.go#L41) is the metric.
