### ISSUE TITLE
Log Cache does not support PromQL range queries

### ISSUE THREAD

**Issue by dtimm** [cloudfoundry/log-cache#71]
Currently log cache only supports instant queries, which is great for things like alerting where we only need a few data points, but not so great for looking at a result over time for things like charting.

It would be great if we could use log cache to chart the results of a query over time.

Prometheus range query documentation:
https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

**Comment by johannaratliff** [comment]
Hey @dtimm, We support range over time with the PromQL [query itself](https://prometheus.io/docs/prometheus/latest/querying/basics/#range-vector-selectors) instead of a unique range query endpoint. An example would be 
```
curl -G "http://<log-cache-addr>:8080/v1/promql" --data-urlencode 'query=metrics{source_id="source-id-1"}[5m]'
```
Does that fulfill your use case?

**Comment by dtimm** [comment]
@johannasmith , a range query runs the same query repeatedly over a period of time, retrieving a window of time on the query itself rather than the metric/metrics from which it is composed. To duplicate the functionality, we have to run multiple queries against the `/v1/promql` endpoint with a time offset on each one.

**Comment by toddboom** [comment]
This is fixed in master.
