### ISSUE TITLE
Log Cache PromQL endpoint cannot handle nanosecond time

### ISSUE THREAD

**Issue by trevorwhitney** [cloudfoundry/log-cache#74]
The prometheus web-ui queries the backend with time in a weird format:
`time=1529079064.036`

We get a syntax error with the query that the prometheus UI generates but if we remove the decimal it does not throw an error: 

```
{"error":"strconv.ParseInt: parsing \"1529079064.036\": invalid syntax","code":3}
```

We don't get any data until we remove the time parameter completely, though this is likely a spurious detail related to our data-set. Here was our complete query:

```
query=server_up_time%7Bsource_id%3D%22uaa%22%7D&time=1529079064.036&_=1529078800252
```

**Comment by colins** [comment]
This seems to have been a misunderstanding of the log cache /promql endpoint

**Comment by toddboom** [comment]
I believe this was resolved through the aforementioned Pivotal Tracker story and just needs to be closed out.
