### ISSUE TITLE
Events are always added to promql query results

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/log-cache#81]
https://github.com/cloudfoundry/log-cache/blob/ce3b5f4427bd54e8bd734e0af224c0a6ab2fbf32/internal/promql/promql.go#L266-L301

As you see here, since the default case is adding a metric unless continue is called, events are always added as 0 value metrics to promql results.

**Comment by toddboom** [comment]
@kitemongerer nice catch! this should be fixed in master now.
