### ISSUE TITLE
Nozzle does not shed load when overwhelmed

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#82]
When the log-cache-nozzle is unable to keep up, the gRPC stream client buffers data aggressively. This causes memory to start swapping, and exacerbates the issue.

This is from an overwhelmed nozzle via `top`:
```
5257 vcap      10 -10 4397404 2.369g      0 S  0.4 65.6   3:20.45 log-cache-nozzl
```
where `2.369g` is under the `RES` column and `65.6` is under `%MEM`.

**Comment by toddboom** [comment]
@apoydence Is there a good place to see examples of this happening in the wild?

**Comment by toddboom** [comment]
This is fixed now. We've changed the nozzle architecture a bit:
https://github.com/cloudfoundry/log-cache/commit/c916ea211d263a099ecfeffac9ca638b40e7504f
