### ISSUE TITLE
The /read endpoint returns 404 when the user has access to more than 50 apps

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/log-cache#98]
## What

We've upgraded log-cache from 2.0.1 to 2.0.2.

When the user has access to more than 50 apps (more correctly /v3/apps returns multiple pages) then the following error is written in the log-cache-cf-auth-proxy logs:

```
2019/02/01 11:48:34.679056 CAPI request (/v3/apps) returned: 401
2019/02/01 11:48:34.679118 failed CAPI request (/v3/apps) with status: 401 (Unauthorized)
```

We suspect the http request reuse in capi_client.go might cause the problem, but we haven't debugged it further.

The problem didn't exist on 2.0.1.

## Versions

log-cache: v2.0.2
cf-deployment: 6.10.0

**Comment by johannaratliff** [comment]
[Fixed](https://www.pivotaltracker.com/story/show/163785764).

**Comment by jtuchscherer** [comment]
Thanks for reporting this @bandesz
