### ISSUE TITLE
log-cache-nozzle shows after update to 2.1.0 100% CPU load

### ISSUE THREAD

**Issue by johha** [cloudfoundry/log-cache#99]
Hi,

with the CF v7.2.0 update the log-cache version gets bumped to 2.1.0.
With that version we see 100% CPU load in our dashboards:
<img width="706" alt="screenshot 2019-02-06 at 15 56 21" src="https://user-images.githubusercontent.com/45264872/52349929-ce9d0980-2a27-11e9-9030-5723688b1e30.png">

After switching back to log-cache 2.0.2 (still with CF v7.2.0) the CPU usage is back to normal:
<img width="706" alt="screenshot 2019-02-06 at 15 44 47" src="https://user-images.githubusercontent.com/45264872/52350030-fc824e00-2a27-11e9-9358-91bc3164019f.png">

Could you please check if there is an issue?

**Comment by johannaratliff** [comment]
Hi @johha, for the most recent nozzle, we made some optimizations in the `2.1.0` release that removed the memory strain the nozzle ingress was causing (thus allowing more memory usage for the cache itself). This change caused the nozzle/ingress to be CPU bound instead, so it is definitely a visible consequence. We do see the same 100% CPU but we believe it is just nozzle greedily trying to ingress as quickly as possible. 

Do you have any performance issues or bugs that might be connected to high CPU?

**Comment by johha** [comment]
We didn't see any impacts so far. 
We'll continue testing and reopen the issue if problems occur.

Thanks for the explanation 👍
